Feature/#39 add logout
Team-Maple-Leaf/MapleJudgePlatform-backend pull request #40
Opened 2022-10-29 04:36 UTC by ur2e

- 로그인 성공 후 answer 조회
![image](https://user-images.githubusercontent.com/45191069/198814110-c7e304ff-1ed5-4193-9028-27f968dc8d2d.png)

- 토큰과 함께 로그아웃 요청
![image](https://user-images.githubusercontent.com/45191069/198814125-89dfef4c-8ab5-42e3-8009-f2eafdb12b87.png)

- 로그아웃 시 사용한 토큰으로 answer 조회 
![image](https://user-images.githubusercontent.com/45191069/198814131-6e0fa626-9834-4e1f-86bf-c8b66295ada0.png)

2022-10-29 12:42 UTC, level120 requested changes

2022-10-29 12:42 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/exception/JwtAuthenticationEntryPoint.java
> +        System.out.println("엔트리포인트에 등장 ~ ");
디버깅용 코드 같은데 없애는 것이 좋지 않을까요?

2022-10-29 12:42 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtAuthenticationFilter.java
> +                    SecurityContextHolder.getContext().setAuthentication(authentication);
들여쓰기가 한번 더 들어간 것 같아요.

2022-10-29 12:42 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
함수 이름을 보면 expiration을 줄 것 같지만 실제 구현은 그렇지 않네요, 메서드 이름을 변경하거나 반환하는 로직을 변경해야 할 것 같아요.

2022-10-29 12:42 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
보통 boolean 타입으로 반환하는 경우는 exception을 내지 않아요...

2022-10-29 15:04 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
```suggestion
    public boolean isTokenLogout(String token) {
        String isLogout = (String) redisTemplate.opsForValue().get(token);
        return !StringUtils.hasText(isLogout);
    }
```

2022-10-31 14:49 UTC, ur2e commented on backend/src/main/java/org/mapleleaf/backend/exception/JwtAuthenticationEntryPoint.java
> +        System.out.println("엔트리포인트에 등장 ~ ");
머쓱... ^^ ; ;;

2022-11-01 13:24 UTC, ur2e commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
<img width="60" alt="image" src="https://user-images.githubusercontent.com/45191069/199243479-e8757f9a-294a-41a4-a5be-cee2b1e62615.png">

해당 함수가 반환하는 값이 토큰의 남은 유효기간이라 getExpiration 으로 하였습니다 ! 혹시 getExpirationTime이 더 적합할까요?

2022-11-01 13:30 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
만료 기간 그대로 반환하는것이 아니고 계산해서 반환해주니 후자 `getExpirationTime`이 좋을 것 같아요

2022-11-01 13:35 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/exception/JwtAuthenticationEntryPoint.java
>          }
위에 403 만료된 토큰이랑 여기 둘 다 401이 맞을 것 같은데 어떠신가요?
403은 권한이 없어 실패하지만 401은 인증에 실패한 것이라서요.

2022-11-01 13:35 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
요건 그대로인데 어떻게 하기로 결정하셨나요?

2022-11-01 13:37 UTC, ur2e commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
이것은 제가 주말에 다시 고민해보고 수정해도 괜찮을까요?

2022-11-01 13:38 UTC, ur2e commented on backend/src/main/java/org/mapleleaf/backend/exception/JwtAuthenticationEntryPoint.java
>          }
바로 반영해서 다시 리뷰요청 드리겠습니답 ! 감사합니다 !

2022-11-01 23:21 UTC, ur2e commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
수정했습니다 ! 😄 반환 값에 맞는 함수명이 맞는지 더 신경쓰면서 코드 작성하겠습니답 ~!

2022-11-04 14:04 UTC, level120 commented on backend/src/main/java/org/mapleleaf/backend/jwt/JwtProvider.java
> +    }
요건 만약에 진행하신다면 별도 이슈를 만들어서 하시죠~

2022-11-04 14:04 UTC, level120 approved these changes

2022-11-04 14:26 UTC, leedonggyu1848 approved these changes

2022-11-04 14:26 UTC, merged